import styles from "../../styles/article.quote.module.css";

export default function Quote() {

    const html = `<div panelwrapperprops="[object Object]" type="" aria-controls="" class="row max-width--75 sm-align--center md-align--right" api="[object Object]"><div panelwrapperprops="[object Object]" type="" aria-controls="" class="sm--12 md--5 lg--5 xl--6 md-mb--2 lg-mb--0" data-region="faq content" id="persFAQContent" api="[object Object]"><div panelwrapperprops="[object Object]" aria-controls="" class="row" api="[object Object]"><div panelwrapperprops="[object Object]" aria-controls="" class="sm--12 sm-pl--1 sm-text-align--left sm-mt--1-half sm-mb--1-half md-mt--2-half lg-mt--3 md-mb--2-half lg-mb--0 xl-mb--1 lg-pr--3 columns" api="[object Object]"><p class="sm-font-size--28 sm-line-height--2 heebo font-weight--bold" panelwrapperprops="[object Object]" aria-controls="" data-meta="quote-heading" api="[object Object]"> Any Canadian can open an <span aria-hidden="true">RESP</span><span class="show-for-sr">R E S P</span> – you don’t need to be related to the child who will use the money. </p><svg width="126" height="5" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 126 5" focusable="false" uuid="65d9121456c141948f9468eb65ac692b" api="[object Object]" class="sm-mr--quarter sm-color-fill--white icon--colour-line-article-quotes"><defs><style>.__xO0Xuh0__a{fill:none;stroke:#0075be;stroke-linecap:round;stroke-linejoin:round;stroke-width:5px;}</style></defs><line class="__xO0Xuh0__a " x1="3" y1="2.5" x2="123" y2="2.5"></line></svg></div></div></div><div panelwrapperprops="[object Object]" type="" aria-controls="" class="hide-for-sm-only md--6 xl--4 md-mr--1-half" data-region="faq content" id="persFAQContent2" api="[object Object]"><picture class=""><source media="(min-width: 768px)" srcset="https://www.bmo.com/dist/images/personal/investments/learning-centre/resp_article_pullquote_482x249.jpg"><source media="(min-width: 376px)" srcset="https://www.bmo.com/dist/images/personal/investments/learning-centre/resp_article_pullquote_352x182.jpg"><source media="(max-width: 375px)" srcset="https://www.bmo.com/dist/images/personal/investments/learning-centre/resp_article_pullquote_482x249.jpg"><img alt="In front of a Canadian flag, a diploma is leaned up against a graduation cap that sits on top of a stack of books" class="sm-border-radius--1 sm-box-shadow--layer-level-2" src="https://www.bmo.com/dist/images/personal/investments/learning-centre/resp_article_pullquote_482x249.jpg"></picture></div></div>`;
    return ( 
        <>
        <div dangerouslySetInnerHTML={{__html: html }}></div>
        </>
    );
};